/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ServicosController;
import model.Servicos;
import tools.CaixaDeDialogo;

/**
 *
 * @author Guilherme
 */
public class TelaServicos extends javax.swing.JFrame {

    /**
     * Creates new form TelaServicos
     */
    ServicosController servicos;
    
    public TelaServicos() {
        initComponents();
        atualizarTabela();
    }
    public void limparTela(){
        txtValor.setText("");
        jtxtDsServico.setText("");
        lblId.setText("ID");
        
    }
    
    public void atualizarTabela(){
        servicos = new ServicosController();
        servicos.preencher(jtbServicos);
    }
    
    public void preencherCampos(Servicos objeto){
        lblId.setText(String.valueOf(objeto.getId_servico()));
        jtxtDsServico.setText(objeto.getDs_servico());
        txtValor.setText(String.valueOf(objeto.getVlr_servico()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbServicos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtDsServico = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbServicosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbServicos);

        jButton1.setText("jButton1");

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtxtDsServico.setColumns(20);
        jtxtDsServico.setRows(5);
        jScrollPane2.setViewportView(jtxtDsServico);

        jLabel2.setText("Descrição serviço");

        jLabel3.setText("Valor");

        lblId.setText("ID");

        jButton3.setText("Salvar/Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(170, 170, 170)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //botao fechar
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    //clicar na linha selecionada
    private void jtbServicosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbServicosMousePressed
       int linhaSelecionada = jtbServicos.getSelectedRow();
       
       String codigo = jtbServicos.getModel().getValueAt(linhaSelecionada, 0).toString();
       
       servicos = new ServicosController();
       Servicos objeto =  servicos.buscar(codigo);
       
       if(objeto != null){
           preencherCampos(objeto);
       }else {
           CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao preencer mause preses" );
       }
       
    }//GEN-LAST:event_jtbServicosMousePressed

    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        limparTela();
    }//GEN-LAST:event_jButton4ActionPerformed
    //botao adicionar servico
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try{
           
    
       Servicos servicos;
       
       //se o id setado na label da tela permanecer padrao id ele ira inserir 
       //o label id so ira mudar quando um campo for selecionado
       if(lblId.getText().equals("ID")){
           
       
       /*caso a validacao encontre algum erro a mesma retornara -1*/
       double validacao = validarDados();
       
       if(validacao == -1 ){
            CaixaDeDialogo.obterinstancia().exibirMensagem("erro ");
            
      
       }else{
           //se nao encontrado nenhum erro 
           servicos = guardarDados(validacao, 0);
           ServicosController servicoController = new ServicosController();
          
           if(servicoController.incluir(servicos)){
               limparTela();
               atualizarTabela();
               CaixaDeDialogo.obterinstancia().exibirMensagem("Servico adicionado com sucesso ");
                

           }else{
               System.out.println("erro ao incluir btn incluir ");
               limparTela();
           }
           
       }
           
       }else {
           
           double validacao = validarDados();
           if(validacao == -1){
               
           }else {
               servicos = guardarDados(validacao,1);
               ServicosController serController = new ServicosController();
               
               if(serController.alterar(servicos)){
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Servico modificado com sucesso ");
                    limparTela();
                    atualizarTabela();

               }else{
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao modificar o servico ");

               }
           }
           
       }
       
       
       }catch(Exception e){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro adicionar servico tela servico "+e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    public Servicos guardarDados(double validacao, int tpGuardarDados){
        try{
        Servicos objServicos = new Servicos();
        objServicos.setDs_servico(jtxtDsServico.getText());
        objServicos.setVlr_servico(validacao);
       
        if(tpGuardarDados == 1){
            objServicos.setId_servico(Integer.parseInt(lblId.getText()));
        }
        
        return objServicos;
        }catch(Exception e){
            CaixaDeDialogo.obterinstancia().exibirMensagem("erro guardar dados tela servicos"+e);
            return null;

        }   
        
    } 
    
    public double validarDados(){
        try{
            
       
        double valor = 0.00;
        
        if(jtxtDsServico.getText().equals("") ){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Descrição vazia");
            return -1;
            
        }
       
        if(txtValor.getText().equals("") ){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Valor do serviço nullo");
            return -1;
           
        }else {
            
            String novoValor;
            novoValor = txtValor.getText().toString();
            novoValor = novoValor.replace(",", ".");
            
            
            
            valor = Double.parseDouble(novoValor);
            
            if(valor < 0 ){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Valor menor do que 0.00");
                return -1;

            }
            
            return valor;
        }
        }catch(NumberFormatException e){
            CaixaDeDialogo.obterinstancia().exibirMensagem("erro validar dados tela servicos "+e);
            return -1;
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaServicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtbServicos;
    private javax.swing.JTextArea jtxtDsServico;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
