/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import contoller.MovimentacoesController;
import tools.CaixaDeDialogo;
import tools.Combos;

/**
 *
 * @author guilherme.w1
 */
public class TelaMovimetacoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaMovimetacoes
     */
    
    MovimentacoesController mvController;
    Combos comboMovimentacao;
    
    public TelaMovimetacoes() {
        initComponents();
        
        atualizarTabela("p");
        
               
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblMovimentos = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbMovimentacoesPendentes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmenuAdicionar = new javax.swing.JMenuItem();
        jmenuEncerrados = new javax.swing.JMenuItem();
        jmenuPendentes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMovimentos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblMovimentos.setText("Pendentes");

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(lblMovimentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1)
                    .addComponent(lblMovimentos))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jtbMovimentacoesPendentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbMovimentacoesPendentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbMovimentacoesPendentesMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtbMovimentacoesPendentes);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Movimentações");

        jmenuAdicionar.setText("Adicionar");
        jmenuAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuAdicionarActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuAdicionar);

        jmenuEncerrados.setText("Encerrados");
        jmenuEncerrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuEncerradosActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuEncerrados);

        jmenuPendentes.setText("Pendentes");
        jmenuPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuPendentesActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuPendentes);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Proprietarios");

        jMenuItem1.setText("Adicionar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Serviços");

        jMenuItem7.setText("Servicos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Veiculos");

        jMenuItem5.setText("Veiculos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Adiconar veiculos");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Sair");

        jMenuItem4.setText("Sair");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//jmeunu Adicionar movimentações
    private void jmenuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuAdicionarActionPerformed
       TelaAdicionar tela = new TelaAdicionar();
       tela.setVisible(true);
    }//GEN-LAST:event_jmenuAdicionarActionPerformed
    
    //adicionar proprietarios
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaProprietario tela = new TelaProprietario();
        tela.setVisible(true);
              
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        dispose();

    }//GEN-LAST:event_jMenuItem4ActionPerformed
    
    //tela de veiculos
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TelaVeiculo tela = new TelaVeiculo();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        TelaServicos tela = new TelaServicos();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    
    //encerrados
    private void jmenuEncerradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuEncerradosActionPerformed
        atualizarTabela("e");
    }//GEN-LAST:event_jmenuEncerradosActionPerformed

    private void jmenuPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuPendentesActionPerformed
        atualizarTabela("p");
    }//GEN-LAST:event_jmenuPendentesActionPerformed
    
    
    //metodo de clique do mouse para marcar como concluida uma movimentacao
    private void jtbMovimentacoesPendentesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbMovimentacoesPendentesMousePressed
        /*
        int linhaSelecionada = jtbMovimentacoesPendentes.getSelectedRow();
        
        String codigo = jtbMovimentacoesPendentes.getModel().getValueAt(linhaSelecionada, 0).toString();
        */
        
        if(jtbMovimentacoesPendentes.isColumnSelected(3)){
             boolean pergunta = CaixaDeDialogo.obterinstancia()
                            .pedirConfirmacao("Marcar movimentacao como concluida?", "", 'p');
            
             if(pergunta){
                mvController = new MovimentacoesController();
                int linhaSelecionada = jtbMovimentacoesPendentes.getSelectedRow();
                String codigo = jtbMovimentacoesPendentes.getModel().getValueAt(linhaSelecionada, 0).toString();
                int id = Integer.parseInt(codigo);
                
                if(mvController.marcarComoConcluido(id)){
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Movimentacao marcada como concluida");
                    atualizarTabela("p");
                }else{
                    CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao marcar movimentacao");
                }
                
                 
             }
        }
                
        
        
    }//GEN-LAST:event_jtbMovimentacoesPendentesMousePressed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        /*
        MovimentacoesController mv = new MovimentacoesController();
        String a ="2";
        mv.buscar(a);
        */
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMovimetacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMovimetacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMovimetacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMovimetacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMovimetacoes().setVisible(true);
            }
        });
    }
    
    
    
    private void atualizarTabela(String tipo){
        mvController = new MovimentacoesController();
        
        if(tipo.equals("p")){
            lblMovimentos.setText("Pendentes");
            
         
            
        }else if(tipo.equals("e")){
            lblMovimentos.setText("Encerrados");
                    
        }
        mvController.preencher(jtbMovimentacoesPendentes, tipo);
                
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JMenuItem jmenuAdicionar;
    private javax.swing.JMenuItem jmenuEncerrados;
    private javax.swing.JMenuItem jmenuPendentes;
    private javax.swing.JTable jtbMovimentacoesPendentes;
    private javax.swing.JLabel lblMovimentos;
    // End of variables declaration//GEN-END:variables
}
